### ISSUE TITLE
http://repo.varnish-cache.org/ has gone away; varnish::repo needs updating

### ISSUE THREAD

**Issue by cyberscribe** [maxchk/puppet-varnish#148] opened 2017-09-12 13:19 UTC
yumrepo['varnish'] configures the old /etc/yum.repos.d/varnish.repo file, which now causes yum to abort. The packagecloud.io repo is the new place to go, and details on migration are here: https://community.centminmod.com/threads/varnish-repo-failed.12768/

Would be great to see both an updated repo and any code needed to migrate seamlessly in place. For now, I am overriding with 

```
        file { '/etc/yum.repos.d/varnish.repo':
            ensure => absent,
            require => yumrepo['varnish'],
        }
```

and then adding in `/etc/yum.repos.d/varnishcache_varnish41.repo` from a template. Works, but not the most elegant!

**Comment by gozer** [comment] 2017-09-18 14:50
This is a dupe of #146, fixed in #147

**Closed as completed** 2017-09-19 13:15 UTC
